/**
 * Created by chengfulin on 2015/4/10.
 */
var walkes = require('walkes');
var worklist = require('../');
var Set = require('../set');

module.exports = ReachDefinitions;

function ReachDefinitions(cfg) {
    'use strict';
    /// Transfer function of ReachDefinition algorithm with Work list algorithm
    /// input ReachIn set of current node
    /// output ReachOut set of current node
    return worklist(cfg, function (input) {
        if (this.type || !this.astNode)
            return input;
        var kill = this.kill = this.kill || ReachDefinitions.KILL(this.astNode);
        var generate = this.generate = this.generate || ReachDefinitions.GEN(this.astNode);
        return Set.union(Set.minus(input, kill), generate);
    }, {direction: 'forward'});
}

/**
 * Get KILL set
 * @param astNode
 * @returns Set of variable whose definition was defined in astNode
 * @constructor
 */
ReachDefinitions.KILL = function (astNode) {
    'use strict';
    var variables = new Set();
    /// KILL(n)
    /// 1. Variable redefined by assignment expression
    /// 2. Define object property by assignment expression
    /// 3. Update by UpdateExpression
    walkes(astNode, {
        Program: function () {},
        AssignmentExpression: function (node, recurse) {
            if (node.left.type === 'MemberExpression') {
                recurse(node.left.object);
            } else {
                recurse(node.left);
            }
            if (node.right.type === 'AssignmentExpression') {
                recurse(node.right);
            }
        },
        UpdateExpression: function (node, recurse) {
            recurse(node.argument);
        },
        FunctionDeclaration: function () {},
        FunctionExpression: function () {},
        VariableDeclaration: function () {},
        VariableDeclarator: function () {},
        Identifier: function (node) {
            variables.add(node.name);
        }
    });
    return variables;
};

/**
 * Get GEN set
 * @param astNode
 * @returns Set of variable whose definition was not killed in astNode
 * @constructor
 */
ReachDefinitions.GEN = function (astNode) {
    'use strict';
    var variables = new Set();
    /// GEN(n)
    /// 1. Generated by variable declaration
    /// 2. Variable assignment
    /// 3. Update expression
    walkes(astNode, {
        Program: function () {},
        AssignmentExpression: function (node, recurse) {
            if (node.left.type === 'MemberExpression') {
                recurse(node.left.object);
            } else {
                recurse(node.left);
            }
            if (node.right.type === 'AssignmentExpression') {
                recurse(node.right);
            }
        },
        FunctionDeclaration: function () {},
        FunctionExpression: function () {},
        VariableDeclaration: function (node, recurse) {
            node.declarations.forEach(function (elem) {
                recurse(elem);
            });
        },
        VariableDeclarator: function (node, recurse) {
            recurse(node.id);
        },
        UpdateExpression: function (node, recurse) {
            recurse(node.argument);
        },
        Identifier: function (node) {
            variables.add(node.name);
        }
    });
    return variables;
};

